module.exports = [
    { title: 'Gladiator', rating: 8.5 },
    { title: 'The Departed', rating: 8.5 },
    { title: 'The Prestige', rating: 8.5 },
    { title: 'Pulp Fiction', rating: 8.9 },
    { title: 'Schindler\'s List', rating: 8.9 },
    { title: 'Forrest Gump', rating: 8.8 },
    { title: 'The Return of the King', rating: 8.9 },
    { title: 'Fight Club', rating: 8.8 },
    { title: 'Inception', rating: 8.8 },
    { title: 'The Matrix', rating: 8.7 },
    { title: 'Silence of the Lambs', rating: 8.6 },
    { title: 'A New Hope', rating: 8.6 },
    { title: 'The Godfather II', rating: 9.0 },
    { title: 'Goodfellas', rating: 8.7 },
    { title: 'Fellowship of the Ring', rating: 8.7 },
    { title: 'The Two Towers', rating: 8.7 },
    { title: 'The Empire Strikes Back', rating: 8.7 },
    { title: 'Se7en', rating: 8.6 },
    { title: 'The Usual Suspects', rating: 8.5 },
    { title: 'The Lion King', rating: 8.5 },
    { title: 'Saving Private Ryan', rating: 8.6 },
    { title: 'The Green Mile', rating: 8.6 },
    { title: 'Interstellar', rating: 8.6 },
    { title: 'The Godfather III', rating: 7.6 },
    { title: 'The Matrix Reloaded', rating: 7.2 },
    { title: 'The Matrix Revolutions', rating: 6.7 },
    { title: 'The Social Network', rating: 7.7 },
    { title: 'Titanic', rating: 7.8 },
    { title: 'Jurassic Park', rating: 8.1 },
    { title: 'The Avengers', rating: 8.0 },
    { title: 'Django Unchained', rating: 8.4 },
    { title: 'The Wolf of Wall Street', rating: 8.2 },
    { title: 'Inglourious Basterds', rating: 8.3 },
    { title: 'The Revenant', rating: 8.0 },
    { title: 'The Grand Budapest Hotel', rating: 8.1 },
    { title: 'The Godfather II', rating: 9.0 },
    { title: 'A Beautiful Mind', rating: 8.2 },
    { title: 'The Truman Show', rating: 8.1 },
    { title: 'Braveheart', rating: 8.3 },
    { title: 'American Beauty', rating: 8.3 },
    { title: 'The Sixth Sense', rating: 8.1 },
    { title: 'The Shining', rating: 8.4 },
    { title: 'The Terminator', rating: 8.0 },
    { title: 'Terminator 2: Judgment Day', rating: 8.5 },
    { title: 'Aliens', rating: 8.3 },
    { title: 'The Good, the Bad and the Ugly', rating: 8.8 },
    { title: 'A Clockwork Orange', rating: 8.3 },
    { title: 'Full Metal Jacket', rating: 8.3 },
    { title: '2001: A Space Odyssey', rating: 8.3 },
    { title: 'Blade Runner', rating: 8.1 },
    { title: 'The Great Gatsby', rating: 7.2 },
    { title: 'The Wizard of Oz', rating: 8.0 },
    { title: 'E.T. the Extra-Terrestrial', rating: 7.8 },
    { title: 'Good Will Hunting', rating: 8.3 },
    { title: 'American History X', rating: 8.5 },
    { title: 'Requiem for a Dream', rating: 8.3 },
    { title: 'Memento', rating: 8.4 },
    { title: 'The Green Mile', rating: 8.6 },
    { title: 'The Fellowship of the Ring', rating: 8.8 },
    { title: 'The Two Towers', rating: 8.7 },
    { title: 'The Return of the King', rating: 8.9 },
    { title: 'An Unexpected Journey', rating: 7.8 },
    { title: 'The Desolation of Smaug', rating: 7.8 },
    { title: 'The Battle of the Five Armies', rating: 7.4 },
    { title: 'The Lion, the Witch and the Wardrobe', rating: 6.9 },
    { title: 'Prince Caspian', rating: 6.5 },
    { title: 'The Voyage of the Dawn Treader', rating: 6.3 },
    { title: 'The Curse of the Black Pearl', rating: 8.0 },
    { title: 'Dead Man\'s Chest', rating: 7.3 },
    { title: 'At World\'s End', rating: 7.1 },
    { title: 'On Stranger Tides', rating: 6.6 },
    { title: 'The Lion King', rating: 8.5 },
    { title: 'Beauty and the Beast', rating: 7.1 },
    { title: 'Aladdin', rating: 8.0 },
    { title: 'Toy Story', rating: 8.3 },
    { title: 'Finding Nemo', rating: 8.1 },
    { title: 'Frozen', rating: 7.4 },
    { title: 'Zootopia', rating: 8.0 },
    { title: 'Moana', rating: 7.6 },
    { title: 'The Incredibles', rating: 8.0 },
    { title: 'Shrek', rating: 7.8 },
    { title: 'Wall-E', rating: 8.4 },
    { title: 'Up', rating: 8.2 },
    { title: 'Inside Out', rating: 8.1 },
    { title: 'Ratatouille', rating: 8.0 },
    { title: 'The Princess Bride', rating: 8.1 }
];